### ISSUE TITLE
docker compose setup for development and testing

### ISSUE THREAD

**Issue by dnephin** [assembl/assembl#3]
Hello,

I would like to contribute [Dockerfiles](https://www.docker.com/) and a [docker-compose.yaml](https://github.com/docker/fig) for interactive development and testing.  

There are a few advantages to a setup like this, notably:
- you can closely mimic production in development by having separate "hosts" for each service (memcache, postgres, etc). You can also ensure that versions and configuration of these services matches production configuration.
- you're able to get started with a project by just running a couple of commands (no manual steps to setup config and other services on your desktop.
  
  ```
  git clone ...
  docker-compose up
  ```

Is this something you would be interesting in accepting a pull request for?

**Comment by benoitg** [comment]
I have no objection in principle.

However, not being familiar with docker, I have no idea how hard it would be for you to keep it in sync with our own version management (a combinasion of Fabric, Bower and pip)

**Comment by dnephin** [comment]
It compliments bower and pip quite well. In a lot of ways it fulfils the same role as many of these fabric tasks.

Instead of duplicating them, I could have it just run the fabric task to do the installation of packages. The downside to that approach is that changes to the `fabfile.py` would require rebuilding the whole image, and an ssh server has to be installed in the containers.

I might start there and see how it looks.

**Comment by benoitg** [comment]
There is no way around containers running a ssh server.  Several of the fabric tasks are crucial to the operation of an assembl server, not just it's installation.

**Comment by dnephin** [comment]
Cool, I will go with that approach.  Since most of the fabric tasks split installation of dependencies from the build work, it should be possible to structure the `Dockerfile` so that rebuilds are pretty fast (unless the `fabfile.py` changes, which causes everything to be rebuilt).

**Comment by jmatsushita** [comment]
Any interest in continuing this thread? The current complex installation setup might limit adoption. I know it prevents me from spinning up a test server and I'd really like to test! :)

**Comment by maparent** [comment]
Good day, Jun! 

We definitely see a better packaging story as a very important item on our roadmap. We have not decided on a solution yet, though Daniel's excellent work on Docker is a good starting point. We do welcome such contributions, though of course merging always involves some back and forth, which is why Daniel's contribution was not merged yet. But if he's too busy to adjust his pull request until we're both happy with it, we do intend to take it up and merge it eventually. We're currently occupied with other commitments, so we have not yet scheduled work on this, but I suspect it will come shortly after the end of the catalyst project (end of September). We would assist in the meantime if Daniel (hello!) or someone else wants to take up that work. 

We are also open to alternative packaging solutions, especially since there is no reason to chose only one; I see you're suggesting sandstorm. We could also make it a point to assist you if you want to have a go at this.

**Comment by jmatsushita** [comment]
Wondering if @dnephin has thoughts on this?

**Comment by dnephin** [comment]
I am interested in continuing the work on the docker packaging, but I can't make any firm commitments about when exactly. I hope to get some time over the next month to work on it.

**Comment by maparent** [comment]
Excellent! Let us know when you think you have time, we'll try to bump priority so we can set time aside to give you close support.
